# Our Quiz:  Exodus 20 (NIV)

1. You shall have no other gods before me.
2. You shall not make for yourself an image in the form of anything in heaven above or on the earth beneath or in the waters below... 
3. You shall not misuse the name of the Lord your God...
4. __________________________________ ???
5. “Honor your father and your mother...
6. You shall not murder.
7. You shall not commit adultery.
8. You shall not steal.
9. You shall not give false testimony against your neighbor.
10. You shall not covet your neighbor’s house. You shall not covet your neighbor’s wife, or his male or female servant, his ox or donkey, or anything that belongs to your neighbor.

#  Tension Quotes

##  Work,  Ecclesiastes 5:18-20, NIV

18 This is what I have observed to be good: that it is appropriate for a person to eat, to drink and **to find satisfaction in their toilsome labor under the sun during the few days of life God has given them—for this is their lot**. 19 Moreover, when God gives someone wealth and possessions, and the ability to enjoy them, to accept their lot and **be happy in their toil—this is a gift of God.** 20 They seldom reflect on the days of their life, because God keeps them occupied with gladness of heart.


## Worry Not,  Ecclesiastes 4:4-6, NIV

4 And I saw that all toil and all achievement spring from one person’s envy of another. This too is meaningless, a chasing after the wind.

5 Fools fold their hands
    and ruin themselves.
6 Better one handful with tranquillity
    than two handfuls with toil
    and chasing after the wind.
    
##  Work,  Matthew 25:14-30, NIV

The Parable of the Bags of Gold
14 “Again, it will be like a man going on a journey, who called his servants and entrusted his wealth to them. 15 To one he gave five bags of gold, to another two bags, and to another one bag,[a] each according to his ability. Then he went on his journey. 16 The man who had received five bags of gold went at once and put his money to work and gained five bags more. 17 So also, the one with two bags of gold gained two more. 18 But the man who had received one bag went off, dug a hole in the ground and hid his master’s money.

19 “After a long time the master of those servants returned and settled accounts with them. 20 The man who had received five bags of gold brought the other five. ‘Master,’ he said, ‘you entrusted me with five bags of gold. See, I have gained five more.’

21 “His master replied, ‘Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things. Come and share your master’s happiness!’

22 “The man with two bags of gold also came. ‘Master,’ he said, ‘you entrusted me with two bags of gold; see, I have gained two more.’

23 “His master replied, ‘Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things. Come and share your master’s happiness!’

24 “Then the man who had received one bag of gold came. ‘Master,’ he said, ‘I knew that you are a hard man, harvesting where you have not sown and gathering where you have not scattered seed. 25 So I was afraid and went out and hid your gold in the ground. See, here is what belongs to you.’

26 “His master replied, ‘You wicked, lazy servant! So you knew that I harvest where I have not sown and gather where I have not scattered seed? 27 Well then, you should have put my money on deposit with the bankers, so that when I returned I would have received it back with interest.

28 “‘So take the bag of gold from him and give it to the one who has ten bags. 29 For whoever has will be given more, and they will have an abundance. Whoever does not have, even what they have will be taken from them. ***30 And throw that worthless servant outside, into the darkness, where there will be weeping and gnashing of teeth.’***


## Worry Not,  Matthew 6: 28-31, NIV

28 “And why do you worry about clothes? See how the flowers of the field grow. They do not labor or spin. 29 Yet I tell you that not even Solomon in all his splendor was dressed like one of these. 30 If that is how God clothes the grass of the field, which is here today and tomorrow is thrown into the fire, will he not much more clothe you—you of little faith? 31 **So do not worry, saying, ‘What shall we eat?’ or ‘What shall we drink?’ or ‘What shall we wear?’**